service: github-aws-cicd
# frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  RandomGenerator:
    handler: src/handler.generateRandomNumber
    timeout: 60
    memorySize: 128 # mb
